/**
 * Randogram - Visual byte distribution inspector for nexid
 *
 * Generates XIDs and renders terminal visualizations to spot
 * patterns, biases, or anomalies in the generated bytes.
 *
 * Usage: npx tsx scripts/randogram.ts [count=200] [--cross-second] [--no-color]
 */

import { init } from '../src/node';

// ANSI 256-color grayscale (232-255 = 24 grays)
function byteToAnsi(b: number): string {
  const gray = 232 + Math.floor((b / 255) * 23);
  return `\x1b[48;5;${gray}m  \x1b[0m`;
}

// ASCII fallback
const RAMP = ' .:-=+*#%@';
function byteToChar(b: number): string {
  return RAMP[Math.floor((b / 255) * (RAMP.length - 1))];
}

const COMPONENTS = [
  { label: 'TIME', offset: 0, width: 4, fixed: false },
  { label: 'MID', offset: 4, width: 3, fixed: true },
  { label: 'PID', offset: 7, width: 2, fixed: true },
  { label: 'CTR', offset: 9, width: 3, fixed: false },
] as const;

function bold(s: string): string {
  return `\x1b[1m${s}\x1b[0m`;
}

function renderHeatmap(ids: Uint8Array[], useColor: boolean, label: string, machineId: string, processId: number) {
  console.log(`\n${bold(`=== ${label} ===`)}`);
  console.log(`${ids.length} XIDs | machine=${machineId} pid=${processId}\n`);

  // Render each component as a separate grid, tiling XIDs left-to-right
  const byteW = useColor ? 2 : 1; // chars per byte cell
  const termWidth = process.stdout.columns || 100;
  const labelCol = 6; // left margin for row labels

  for (const comp of COMPONENTS) {
    const cellW = comp.width * byteW; // chars per XID in this component
    const gap = 0; // no gap between XIDs for a dense heatmap
    const colsPerRow = Math.max(1, Math.floor((termWidth - labelCol) / (cellW + gap)));
    const totalRows = Math.ceil(ids.length / colsPerRow);

    const note = comp.fixed ? ' (fixed)' : '';
    console.log(`  ${bold(comp.label)}${note}  [${comp.width} bytes × ${ids.length} IDs → ${colsPerRow}×${totalRows} grid]`);

    // X-axis tick marks
    const ticks = [0, Math.floor(colsPerRow / 4), Math.floor(colsPerRow / 2), Math.floor((3 * colsPerRow) / 4), colsPerRow - 1];
    let tickLine = ' '.repeat(labelCol);
    for (let col = 0; col < colsPerRow; col++) {
      if (ticks.includes(col)) {
        tickLine += String(col).padEnd(cellW);
      } else {
        tickLine += ' '.repeat(cellW);
      }
    }
    console.log(tickLine);

    for (let row = 0; row < totalRows; row++) {
      const rowIdx = row * colsPerRow;
      const prefix = rowIdx % 50 === 0 || row === 0 ? String(rowIdx).padStart(labelCol - 1) + ' ' : ' '.repeat(labelCol);
      let line = prefix;
      for (let col = 0; col < colsPerRow; col++) {
        const idx = rowIdx + col;
        if (idx >= ids.length) break;
        const id = ids[idx];
        for (let j = comp.offset; j < comp.offset + comp.width; j++) {
          line += useColor ? byteToAnsi(id[j]) : byteToChar(id[j]);
        }
      }
      if (useColor) line += '\x1b[0m';
      console.log(line);
    }
    console.log();
  }
}

function computeFreqs(ids: Uint8Array[], offset: number, width: number) {
  const freqs = new Uint32Array(256);
  let total = 0;
  for (const id of ids) {
    for (let j = offset; j < offset + width; j++) {
      freqs[id[j]]++;
      total++;
    }
  }
  return { freqs, total };
}

function renderHistogram(ids: Uint8Array[]) {
  console.log(`\n${bold('=== BYTE FREQUENCY (16-bucket histogram) ===')}\n`);

  const bucketSize = 16;
  const buckets = 256 / bucketSize;
  const barWidth = 40;

  for (const comp of COMPONENTS) {
    const { freqs, total } = computeFreqs(ids, comp.offset, comp.width);

    const bucketCounts = new Float64Array(buckets);
    for (let b = 0; b < 256; b++) {
      bucketCounts[Math.floor(b / bucketSize)] += freqs[b];
    }
    const maxBucket = Math.max(...bucketCounts);

    const note = comp.fixed ? ' (constant per process)' : '';
    console.log(`  ${comp.label}${note} — ${total} samples:`);
    for (let b = 0; b < buckets; b++) {
      const lo = (b * bucketSize).toString(16).padStart(2, '0');
      const hi = ((b + 1) * bucketSize - 1).toString(16).padStart(2, '0');
      const len = maxBucket > 0 ? Math.round((bucketCounts[b] / maxBucket) * barWidth) : 0;
      const bar = '\u2588'.repeat(len) + ' '.repeat(barWidth - len);
      console.log(`    ${lo}-${hi} |${bar}| ${bucketCounts[b]}`);
    }
    console.log();
  }
}

function renderStats(ids: Uint8Array[], label: string) {
  console.log(`${bold(`=== UNIFORMITY: ${label} ===`)}\n`);

  for (const comp of COMPONENTS) {
    const { freqs, total } = computeFreqs(ids, comp.offset, comp.width);

    const expected = total / 256;
    let chiSq = 0;
    let occupied = 0;
    let min = Infinity;
    let max = 0;
    for (let b = 0; b < 256; b++) {
      if (freqs[b] > 0) occupied++;
      if (freqs[b] < min) min = freqs[b];
      if (freqs[b] > max) max = freqs[b];
      chiSq += ((freqs[b] - expected) ** 2) / expected;
    }

    let verdict: string;
    if (comp.fixed) {
      verdict = '\x1b[90mFIXED (expected)\x1b[0m';
    } else if (chiSq < 293) {
      verdict = '\x1b[32mPASS (uniform)\x1b[0m';
    } else if (chiSq < 400) {
      verdict = '\x1b[33mMARGINAL\x1b[0m';
    } else {
      // Check if it's expected behavior
      const note = comp.label === 'TIME' ? ' — same-second IDs are identical' : ' — 20-bit seed caps byte[9]';
      verdict = `\x1b[31mBIASED${note}\x1b[0m`;
    }

    console.log(`  ${comp.label.padEnd(5)} vals=${String(occupied).padStart(3)}/256  range=[${min},${max}]  chi2=${chiSq.toFixed(0).padStart(7)}  ${verdict}`);
  }
  console.log();
}

function renderPerByteStats(ids: Uint8Array[]) {
  console.log(`${bold('=== PER-BYTE POSITION ENTROPY ===')}\n`);

  console.log('  Byte   Unique  Min  Max  Entropy (bits)  Notes');
  console.log('  ----   ------  ---  ---  --------------  -----');

  for (let pos = 0; pos < 12; pos++) {
    const freqs = new Uint32Array(256);
    for (const id of ids) freqs[id[pos]]++;

    let occupied = 0;
    let min = Infinity;
    let max = 0;
    let entropy = 0;
    const n = ids.length;

    for (let b = 0; b < 256; b++) {
      if (freqs[b] > 0) {
        occupied++;
        const p = freqs[b] / n;
        entropy -= p * Math.log2(p);
      }
      if (freqs[b] < min) min = freqs[b];
      if (freqs[b] > max) max = freqs[b];
    }

    const comp = COMPONENTS.find(c => pos >= c.offset && pos < c.offset + c.width)!;
    const maxEntropy = 8.0;
    const pct = ((entropy / maxEntropy) * 100).toFixed(0);
    const bar = '\u2588'.repeat(Math.round((entropy / maxEntropy) * 16));

    let note = '';
    if (comp.fixed) note = `(${comp.label} — fixed)`;
    else if (occupied === 1) note = '(constant)';
    else if (entropy < 2) note = '(low entropy)';
    else if (entropy > 7) note = '(good)';

    console.log(
      `   [${String(pos).padStart(2)}]  ${String(occupied).padStart(4)}   ${String(min).padStart(3)}  ${String(max).padStart(3)}  ${entropy.toFixed(2).padStart(5)} ${bar.padEnd(16)}  ${pct}%  ${note}`,
    );
  }
  console.log();
}

async function main() {
  const args = process.argv.slice(2);
  const count = parseInt(args.find(a => !a.startsWith('-')) || '200', 10);
  const crossSecond = args.includes('--cross-second');
  const useColor = !args.includes('--no-color') && process.stdout.isTTY !== false;

  const gen = init();

  // --- Same-second burst ---
  const burstIds: Uint8Array[] = [];
  for (let i = 0; i < count; i++) {
    burstIds.push(gen.newId().bytes);
  }

  renderHeatmap(burstIds, useColor, 'RANDOGRAM (same-second burst)', gen.machineId, gen.processId);
  renderHistogram(burstIds);
  renderStats(burstIds, 'same-second burst');
  renderPerByteStats(burstIds);

  // --- Cross-second (simulated via different timestamps) ---
  if (crossSecond) {
    const crossIds: Uint8Array[] = [];
    const baseTime = Date.now();

    // Generate IDs across N different seconds to test seed diversity
    const seconds = Math.min(count, 100);
    const perSecond = Math.max(1, Math.floor(count / seconds));

    for (let s = 0; s < seconds; s++) {
      const ts = new Date(baseTime + s * 1000);
      for (let i = 0; i < perSecond; i++) {
        crossIds.push(gen.newId(ts).bytes);
      }
    }

    renderHeatmap(crossIds, useColor, 'RANDOGRAM (cross-second, re-seeded counters)', gen.machineId, gen.processId);
    renderHistogram(crossIds);
    renderStats(crossIds, 'cross-second (counter re-seeded each second)');
    renderPerByteStats(crossIds);
  }
}

main();
